### PR TITLE
[Urgent] LPS-195925

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang, BChan reverted the fix, due to the change can't work on below 7.3. Please see the below error during `ant all` on 7.2.x.
```
uild-common-java.compile:
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal-7.2.x/portal-impl/classes
    [javac] Compiling 2660 source files to /opt/dev/projects/github/liferay-portal-7.2.x/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal-7.2.x/portal-impl/src/com/liferay/portal/service/persistence/impl/OrganizationPersistenceImpl.java:9455: error: cannot find symbol
    [javac] 					organizationModelImpl.getColumnOriginalValue(
    [javac] 					                     ^
    [javac]   symbol:   method getColumnOriginalValue(String)
    [javac]   location: variable organizationModelImpl of type OrganizationModelImpl
```
I only added the commit ac313a3608c002a54527948515ed53fb4238b210 to do the compatibility. I tested the changes on the lower version(7.3.x\7.2.x\7.1.x )  and it was passed.

**Test methods:**
Copy master's `com.liferay.portal.tools.service.builder.jar` with the fix to 7.3.x\7.2.x\7.1.x `tools/sdk/dependencies/com.liferay.portal.tools.service.builder/lib/`, and then run `build-services`. `portal-impl `related classes will be changed with the fix. Module related classes can't be changed because it used the [fixed version](https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/build-buildscript.gradle#L2) to build service. I think this is enough to use the change of portal-impl to test because basically they are same.

On 7.0.x, it didn't exist the `externalReferenceCode` column and is also didn't support the `external-reference-code` attribute for the entity.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward:force
